[project]
name = "rebuild-db"
version = "0.1.0"
description = "Drops and rebuilds a staging db."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "pydantic>=2.12.5",
    "pyodbc>=5.3.0",
    "pyyaml>=6.0.3",
    "rich>=14.3.2",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "icecream>=2.1.10",
    "ipykernel>=7.1.0",
    "ruff>=0.14.14",
]
