USE master;
GO

-- if db exists
IF DB_ID('$(DB_STG_NAME)') IS NOT NULL
BEGIN
    -- disconnect users
    ALTER DATABASE $(DB_STG_NAME) SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE $(DB_STG_NAME);
    PRINT ''
END;
GO

CREATE DATABASE $(DB_STG_NAME);
GO

ALTER DATABASE $(DB_STG_NAME)
SET RECOVERY SIMPLE;
GO

USE $(DB_STG_NAME);
GO
