USE olist_stg;

/*
seller concentration (80/20 rule)
approximately 80% of sales volume is generated by 20% of sellers
want to find seller market share
*/

WITH seller_total_revenue AS (
    SELECT
        -- s.*
        -- s.order_id,
        s.seller_id,
        mn.seller_gen_name,
        COUNT(DISTINCT s.order_id) AS order_count,
        SUM(s.price) AS total_product_revenue,
        SUM(s.freight_value) AS total_freight_revenue,
        SUM(s.price + s.freight_value) AS total_revenue
    FROM sales.vw_sales AS s
        LEFT JOIN sales.dim_seller_gen_names AS mn
            ON s.seller_id = mn.seller_id
    GROUP BY
        s.seller_id,
        mn.seller_gen_name
),

tbl_total_market_revenue AS (
    SELECT
        COUNT(DISTINCT s.order_id) AS market_order_count,
        SUM(s.price) AS total_market_product_revenue,
        SUM(s.freight_value) AS total_market_freight_revenue,
        SUM(s.price + s.freight_value) AS total_market_revenue
    FROM sales.vw_sales AS s
)
-- select
-- *
-- from tbl_total_market_revenue as tmr

SELECT
    -- *
    str.seller_id,
    str.seller_gen_name,
    str.order_count,
    -- str.total_product_revenue,
    -- str.total_freight_revenue,
    str.total_revenue,
    1.0 * str.order_count / tmr.market_order_count AS pc_share_order_counts,
    -- str.total_product_revenue / tmr.total_market_product_revenue as pc_share_product_revenue,
    -- str.total_freight_revenue / tmr.total_market_freight_revenue as pc_share_freight_revenue,
    str.total_revenue / tmr.total_market_revenue AS pc_share_total_revenue
FROM seller_total_revenue AS str
    CROSS JOIN tbl_total_market_revenue AS tmr
-- order by pc_share_total_revenue desc
ORDER BY pc_share_order_counts DESC

/* top pc share of total revenue
seller_id, seller_gen_name, order_count, total_product_revenue, total_freight_revenue, total_revenue, pc_share_order_counts, pc_share_product_revenue, pc_share_freight_revenue, pc_share_total_revenue
4869f7a5dfa277a7dca6462dcf3b52b2, Relojoaria Crono, 1131, 229237.6300, 20155.8100, 249393.4400, 0.011517428894, 0.016987, 0.008993, 0.015849
7c67e1448b00f6e969d365cea6b010ab, Work Design Itaquaquecetuba, 982, 187923.8900, 51612.5500, 239536.4400, 0.010000101834, 0.013926, 0.023029, 0.015222
53243585a1d6dc2643021fd1853d8905, Fone Signal, 358, 222776.0500, 13080.6300, 235856.6800, 0.003645658306, 0.016508, 0.005836, 0.014988
*/

/* top pc share of total revenue
seller_id, seller_gen_name, order_count, total_revenue, pc_share_order_counts, pc_share_total_revenue
4869f7a5dfa277a7dca6462dcf3b52b2, Relojoaria Crono, 1131, 249393.4400, 0.011517428894, 0.015849
7c67e1448b00f6e969d365cea6b010ab, Work Design Itaquaquecetuba, 982, 239536.4400, 0.010000101834, 0.015222
53243585a1d6dc2643021fd1853d8905, Fone Signal, 358, 235856.6800, 0.003645658306, 0.014988
4a3ca9315b744ce9f8e9374361493884, Casa Algodão Ibitinga, 1804, 235359.3000, 0.018370859173, 0.014957
fa1c13f2614d7b5c4749cbc52fecda94, Ouro & Gifting, 584, 202861.6700, 0.005947107404, 0.012891
da8622b14eb17ae2831f4ac5b9dab84a, Sonho & Mesa, 1314, 185192.3200, 0.013380991659, 0.011769
7e93a43ef30c4f03f38b393420bc753a, Pulso Watch, 332, 178838.4200, 0.003380889825, 0.011365
1025f0e2d44d7041d6cf58b6550e0bfa, Espaço Design SaoPaulo, 915, 172860.6900, 0.009317813827, 0.010985
7a67c85e85bb2ce8582c35f2203ad736, The Trend Things, 1159, 162607.2400, 0.011802564180, 0.010333
955fee9216a65b617aa5c0531780ce60, Espaço & Decoração, 1286, 160582.9000, 0.013095856373, 0.010205
*/

/* top pc share of total orders
seller_id, seller_gen_name, order_count, total_revenue, pc_share_order_counts, pc_share_total_revenue
6560211a19b47992c3666cc44a7e94c0, Relojoaria Pulso SaoPaulo, 1847, 150522.0200, 0.018808745506, 0.009565
4a3ca9315b744ce9f8e9374361493884, Casa Algodão Ibitinga, 1804, 235359.3000, 0.018370859173, 0.014957
cc419e0650a3c5ba77189a1882b7556a, Flor Wellness, 1697, 129169.9500, 0.017281235043, 0.008208
1f50f920176fa81dab994f9023523100, Folha & Jardim, 1403, 142037.4800, 0.014287314534, 0.009026
da8622b14eb17ae2831f4ac5b9dab84a, Sonho & Mesa, 1314, 185192.3200, 0.013380991659, 0.011769
955fee9216a65b617aa5c0531780ce60, Espaço & Decoração, 1286, 160582.9000, 0.013095856373, 0.010205
7a67c85e85bb2ce8582c35f2203ad736, The Trend Things, 1159, 162607.2400, 0.011802564180, 0.010333
ea8482cd71df3c1969d7b9473ff13abc, Link Mobile, 1145, 54684.5200, 0.011659996537, 0.003475
4869f7a5dfa277a7dca6462dcf3b52b2, Relojoaria Crono, 1131, 249393.4400, 0.011517428894, 0.015849
3d871de0142ce09b7081e2b9d1733cb1, Rascunho & Criativo, 1076, 116835.8000, 0.010957341724, 0.007424
*/

/*
the seller with pseudonym 'Relojoria Crono' has the highest total revenue market share with 1.58% market share
*/
