/*
Questions generated by claude
https://claude.ai/share/91c86757-2746-4081-9835-9aaf86b5b981
*/

-- ==================================================
-- Strategic Leadership Questions
-- ==================================================

-- ==========
-- Which restaurant segments are most profitable
-- and should we invest more heavily in them?
-- ==========

select
    t.Rank,
    t.Restaurant,
    t.Sales,
    t.Segment
from Top250 t;

select * from Top250;

-- Segment Analysis
select
    sub.*
from (

    select
        t.Segment,
        count(*) as Count,
        sum(t.Sales) as TotalSales,
        sum(t.Units) as TotalUnits,
        cast(round(avg(t.Sales)) as integer) as AvgSales,
        cast(round(avg(t.Units)) as integer) as AvgUnits,
        round(sum(t.Sales)*1.0 / sum(t.Units), 2) as AvgPricePerUnit
    from Top250 t
    group by t.Segment

) sub
where sub.Segment is not null
order by Count desc;

/* Notes
profit = sales - cost
all numeric metrics i have: rank, sales, yoysales, units, yoyunits
from the table, i dont have cost, so i cant find profit

rewrite question:
Q: which segment had the most total sales?
A: Quick Service

segment: Quick Service
count: 47
totalsales: 192,513 million usd
totalunits: 148,629 million units
avgsales: 4,094 million usd
avgunits: 2,162 million units
avgpriceperunit: 1.3 usd

TODO:
Q: should we invest more heavily?
A: 
*/


-- ==========
-- Whats the correlation between number of units and total sales?
-- Is expansion always beneficial?
-- ==========


-- ==========
-- Which restaurants had the strongest/weakest year-over-year sales growth
-- and what patterns emerge?
-- ==========

-- view tables
select
    f.Rank,
    f.Restaurant,
    f.YOYSales
from Future50 f
order by f.YOYSales desc;

select
    t.Rank,
    t.Restaurant,
    t.YOYSales,
from Top250 t
order by t.YOYSales desc;

-- verify no overlap
select
    f.*
from Future50 f
inner join Top250 t
    on f.Restaurant = t.Restaurant;
-- does not print => no overlap
-- can use union all

-- union tables
select
    uni.*
from (

    select
        'F' || f.Rank as Rank,
        f.Restaurant,
        f.YOYSales
    from Future50 f
    union all
    select
        'T' || t.Rank as Rank,
        t.Restaurant,
        t.YOYSales
    from Top250 t

) uni
order by YOYSales desc;

/* Notes
yoy = (cur - prev)/prev = cur/prev - 1
yoysales => growth
yoysales:
    0.5 means grew 50%, so prev. * 1.5
    1.3 means grew 130%, so prev. * 2.3
    -0.2 means shrunk 80%, so prev. * 0.2

Q: which restaurants had the strongest yoy sales growth
A:
Restaurant, YOYSales
Evergreens, 1.305
Clean Juice, 1.219
Slapfish, 0.81
Clean Eatz, 0.797

Q: which restaurants had the weakest yoy sales growth
A:
Restaurant, YOYSales
Houlihan's, -0.212
Old Country Buffet/HomeTown Buffet, -0.188
Fuddruckers, -0.158
McCormick & Schmick's, -0.156
Friendly's, -0.153

Q: what patterns emerge?
A: 
Top250:
Rank, Restaurant, YOYSales
1, McDonald's, 0.049
2, Starbucks, 0.086
3, Chick-fil-A, 0.13
4, Taco Bell, 0.09
5, Burger King, 0.027

the top 5 from Top250 still had growth

TODO:
    wtf union table distrobution
    compare top 5 with others, find where in distrobution
*/

-- ==========
-- Should we focus on quick service or full service restaurants for our next investment?
-- ==========

-- ==================================================
--  Operations & Expansion Questions
-- ==================================================

/*
Whats the optimal number of units for maximising revenue per unit?
*/

-- ==========
-- Are there geographical petterns in restaurant performance we should consider for expansion?
-- ==========

-- view schemas
.schema Future50
.schema Independent100 
.schema Top250 
-- choose union Future50, Independent100

-- view tables
select
    f.Rank,
    f.Restaurant,
    f.City,
    f.State,
    f.Sales
from Future50 f;

select
    i.Rank,
    i.Restaurant,
    i.City,
    i.State,
    i.Sales
from Independent100 i;

-- verify no overlap
select
    f.*
from Future50 f
inner join Independent100 i
    on f.Restaurant = i.Restaurant
-- no overlap
-- therefore can use union all

-- union
create view if not exists v_fi as
select
    'F' || f.Rank as Rank,
    f.Restaurant,
    f.City,
    f.State,
    f.Sales * 1000000 as Sales
from Future50 f
union all
select
    'I' || i.Rank as Rank,
    i.Restaurant,
    i.City,
    i.State,
    i.Sales
from Independent100 i

-- view view
select
    v.*
from v_fi v;


-- grain: City-State
select
    sub.*
from (

    select distinct 
        v.City,
        v.State,
        count(*) as Count,
        sum(v.Sales) as TotalSales
    from v_fi v
    group by
        v.City,
        v.State

) as sub
where Count > 1
order by
    sub.Count desc,
    sub.TotalSales desc


-- grain: State
select
    sub.*
from (

    select distinct 
        v.State,
        count(*) as Count,
        sum(v.Sales) as TotalSales
    from v_fi v
    group by
        v.State

) as sub
where Count > 1
order by
    sub.Count desc,
    sub.TotalSales desc


/* Notes
TODO:
    visualise totalsales on map

grain: City-State
City, State, Count, TotalSales
New York, N.Y., 29, 678473807
Chicago, Ill. 15, 268481978
Las Vegas, Nev., 11, 205296684
Washington, D.C., 10, 206413973
San Francisco, Calif. 7, 150681136

grain: State
State, Count, TotalSales
N.Y., 29, 678473807
Calif., 22, 514769227
Ill., 18, 325484453
Fla., 12, 263847945
Nev., 11, 205296684
*/


/*
Which underperforming chains show potential for turnaround based on their segment/model?
*/

-- ==================================================
-- Competitive Intelligence Questions
-- ==================================================

/*
Who are the top 10 performers and what characteristics do they share?
*/

/*
What percentage of restaurants experienced sales decline vs growth,
and what differentiates them?
*/

-- ==================================================
-- Financial/Investment Questions
-- ==================================================

/*
Whats the relationship between average unit sales and total sales
*/

/*
Which restaurants punch above their weight (high sales with fewer units)?
*/

/*
If we could only invest in 5 restaurant chains, which should they be and why?
*/

