/*
Questions generated by claude
https://claude.ai/share/91c86757-2746-4081-9835-9aaf86b5b981
*/

-- ==================================================
-- Strategic Leadership Questions
-- ==================================================

-- ==========
-- Which restaurant segments are most profitable
-- and should we invest more heavily in them?
-- ==========

SELECT
    t.Rank,
    t.Restaurant,
    t.Sales,
    t.Segment
FROM Top250 AS t;

SELECT * FROM Top250;

-- Segment Analysis
SELECT
    t.Segment,
    COUNT(*) AS Count,
    SUM(t.Sales) AS TotalSales,
    SUM(t.Units) AS TotalUnits,
    CAST(ROUND(AVG(t.Sales)) AS INTEGER) AS AvgSales,
    CAST(ROUND(AVG(t.Units)) AS INTEGER) AS AvgUnits,
    ROUND(SUM(t.Sales) * 1.0 / SUM(t.Units), 2) AS AvgPricePerUnit
FROM Top250 AS t
WHERE t.Segment IS NOT NULL
GROUP BY t.Segment
ORDER BY COUNT(*) DESC;


/* Notes
profit = sales - cost
all numeric metrics i have: rank, sales, yoysales, units, yoyunits
from the table, i dont have cost, so i cant find profit

rewrite question:
Q: which segment had the most total sales?
A: Quick Service

segment: Quick Service
count: 47
totalsales: 192,513 million usd
totalunits: 148,629 million units
avgsales: 4,094 million usd
avgunits: 2,162 million units
avgpriceperunit: 1.3 usd

TODO:
Q: should we invest more heavily?
A:
*/


-- ==========
-- Whats the correlation between number of units and total sales?
-- Is expansion always beneficial?
-- ==========


-- ==========
-- Which restaurants had the strongest/weakest year-over-year sales growth
-- and what patterns emerge?
-- ==========

-- view tables
SELECT
    f.Rank,
    f.Restaurant,
    f.YOYSales
FROM Future50 AS f
ORDER BY f.YOYSales DESC;

SELECT
    t.Rank,
    t.Restaurant,
    t.YOYSales
FROM Top250 AS t
ORDER BY t.YOYSales DESC;

-- verify no overlap
SELECT f.*
FROM Future50 AS f
INNER JOIN Top250 AS t
    ON f.Restaurant = t.Restaurant;
-- does not print => no overlap
-- can use union all

-- union tables
SELECT
    'F' || f.Rank AS Rank,
    f.Restaurant,
    f.YOYSales
FROM Future50 AS f
UNION ALL
SELECT
    'T' || t.Rank AS Rank,
    t.Restaurant,
    t.YOYSales
FROM Top250 AS t
ORDER BY t.YOYSales DESC;


/* Notes
yoy = (cur - prev)/prev = cur/prev - 1
yoysales => growth
yoysales:
    0.5 means grew 50%, so prev. * 1.5
    1.3 means grew 130%, so prev. * 2.3
    -0.2 means shrunk 80%, so prev. * 0.2

Q: which restaurants had the strongest yoy sales growth
A:
Restaurant, YOYSales
Evergreens, 1.305
Clean Juice, 1.219
Slapfish, 0.81
Clean Eatz, 0.797

Q: which restaurants had the weakest yoy sales growth
A:
Restaurant, YOYSales
Houlihan's, -0.212
Old Country Buffet/HomeTown Buffet, -0.188
Fuddruckers, -0.158
McCormick & Schmick's, -0.156
Friendly's, -0.153

Q: what patterns emerge?
A:
Top250:
Rank, Restaurant, YOYSales
1, McDonald's, 0.049
2, Starbucks, 0.086
3, Chick-fil-A, 0.13
4, Taco Bell, 0.09
5, Burger King, 0.027

the top 5 from Top250 still had growth

TODO:
    wtf union table distrobution
    compare top 5 with others, find where in distrobution
*/

-- ==========
-- Should we focus on quick service or full service restaurants for our next investment?
-- ==========

-- ==================================================
--  Operations & Expansion Questions
-- ==================================================

/*
Whats the optimal number of units for maximising revenue per unit?
*/

-- ==========
-- Are there geographical petterns in restaurant performance we should consider for expansion?
-- ==========

-- view schemas
/*

.schema Future50
.schema Independent100
.schema Top250

*/
-- choose union Future50, Independent100

-- view tables
SELECT
    f.Rank,
    f.Restaurant,
    f.City,
    f.State,
    f.Sales
FROM Future50 AS f;

SELECT
    i.Rank,
    i.Restaurant,
    i.City,
    i.State,
    i.Sales
FROM Independent100 AS i;

-- verify no overlap
SELECT f.*
FROM Future50 AS f
INNER JOIN Independent100 AS i
    ON f.Restaurant = i.Restaurant;
-- no overlap
-- therefore can use union all

-- union
CREATE VIEW IF NOT EXISTS v_fi AS
SELECT
    'F' || f.Rank AS Rank,
    f.Restaurant,
    f.City,
    f.State,
    f.Sales * 1000000 AS Sales
FROM Future50 AS f
UNION ALL
SELECT
    'I' || i.Rank AS Rank,
    i.Restaurant,
    i.City,
    i.State,
    i.Sales
FROM Independent100 AS i;

-- view view
SELECT v.*
FROM v_fi AS v;


-- grain: City-State
SELECT DISTINCT
    v.City,
    v.State,
    COUNT(*) AS Count,
    SUM(v.Sales) AS TotalSales
FROM v_fi AS v
GROUP BY
    v.City,
    v.State
HAVING COUNT(*) > 1
ORDER BY
    COUNT(*) DESC,
    SUM(v.Sales) DESC;


-- grain: State
SELECT DISTINCT
    v.State,
    COUNT(*) AS Count,
    SUM(v.Sales) AS Totalsales
FROM v_fi AS v
GROUP BY
    v.State
HAVING COUNT(*) > 1
ORDER BY
    COUNT(*) DESC,
    SUM(v.sales) DESC;


/* Notes
TODO:
    visualise totalsales on map

grain: City-State
City, State, Count, TotalSales
New York, N.Y., 29, 678473807
Chicago, Ill. 15, 268481978
Las Vegas, Nev., 11, 205296684
Washington, D.C., 10, 206413973
San Francisco, Calif. 7, 150681136

grain: State
State, Count, TotalSales
N.Y., 29, 678473807
Calif., 22, 514769227
Ill., 18, 325484453
Fla., 12, 263847945
Nev., 11, 205296684
*/


/*
Which underperforming chains show potential for turnaround based on their segment/model?
*/

-- ==================================================
-- Competitive Intelligence Questions
-- ==================================================

/*
Who are the top 10 performers and what characteristics do they share?
*/

/*
What percentage of restaurants experienced sales decline vs growth,
and what differentiates them?
*/

-- ==================================================
-- Financial/Investment Questions
-- ==================================================

/*
Whats the relationship between average unit sales and total sales
*/

/*
Which restaurants punch above their weight (high sales with fewer units)?
*/

/*
If we could only invest in 5 restaurant chains, which should they be and why?
*/
